name: 'Setup EE addon tests'
description: 'This action sets up test env for EE addons'
author: 'eventespresso'
inputs:
    ee-version:
        required: true
        description: 'EE version to use'
        default: master
runs:
    using: 'composite'
    steps:
        - run: ${{ github.action_path }}/setup-ee-addon-tests.sh ${{ inputs.ee-version }}
          shell: bash
