name: E2E Tests
description: Action for running E2E tests
inputs:
    cafe-repo-branch:
        description: Which branch to use for Cafe repository?
        type: string
        required: true
    use-barista-repo:
        description: Should Barista repo be cloned?
        type: boolean
        required: true
    barista-repo-branch:
        description: Which branch to use for Barista repository?
        type: string
        required: false
    e2e-tests-repo-branch:
        description: Which branch to use for E2E Tests repository?
        type: string
        required: true
runs:
    using: 'node16'
    main: 'dist/index.js'
