name: E2E Tests
description: Action for running E2E tests
inputs:
    cafe_repo_branch:
        description: Which branch to use for Cafe repository?
        type: string
        required: true
    barista_repo_branch:
        description: Which branch to use for Barista repository?
        type: string
        required: false
    e2e_tests_repo_branch:
        description: Which branch to use for E2E Tests repository?
        type: string
        required: true
    skip_tests:
        description: Skip tests (used for cache warm-up workflow)
        type: boolean
        required: false
        default: false
    e2e_gpg_password: # prefixed with e2e_ since org level secret
        description: This value will be used to encrypt artifacts
        type: string
        required: false
        default: ''
    gpg_cipher:
        description: Type of cipher to be used for GPG encryption
        type: string
        required: false
        default: AES256
runs:
    using: node16
    main: dist/index.js
