name: E2E Tests
description: Action for running E2E tests
inputs:
    cafe_repo_branch:
        description: Which branch to use for Cafe repository?
        type: string
        required: true
    barista_repo_branch:
        description: Which branch to use for Barista repository?
        type: string
        required: false
    e2e_tests_repo_branch:
        description: Which branch to use for E2E Tests repository?
        type: string
        required: true
runs:
    using: node16
    main: dist/index.js
