name: 'Checkout and run yarn'
description: 'This action checks out the commit, sets up Node and installs deps using yarn.'
author: 'eventespresso'
inputs:
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
runs:
    using: 'composite'
    steps:
        - name: Checkout the commit
          uses: actions/checkout@v2
          with:
              fetch-depth: ${{ inputs.fetch-depth }}

        - name: Set up Node
          uses: actions/setup-node@v2
          with:
              node-version: lts/*

        - name: Cache dependencies
          id: cache-deps
          uses: actions/cache@v2
          with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Install dependencies
          # install deps only if lockfile has changed
          #   TODO enable 'if' when composite actions support it
          #   if: steps.cache-deps.outputs.cache-hit != 'true'
          run: yarn install --frozen-lockfile
          shell: bash
