name: 'Checkout and run yarn'
description: 'This action checks out the commit, sets up Node and installs deps using yarn.'
author: 'eventespresso'
inputs:
    cache-version:
        required: false
        description: 'used for refreshing the cache by simply changing value to something new'
        default: '1'
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
    token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
runs:
    using: 'composite'
    steps:
        - name: Checkout the commit
          uses: actions/checkout@v3
          with:
              fetch-depth: ${{ inputs.fetch-depth }}
              token: ${{ inputs.token }}

        - name: Set up Node
          uses: actions/setup-node@v2
          with:
              node-version: 16

        - name: Cache dependencies
          id: cache-deps
          uses: actions/cache@v2
          with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules-${{ inputs.cache-version }}-${{ hashFiles('**/yarn.lock') }}

        - name: Install dependencies
          # install deps only if lockfile has changed
          if: steps.cache-deps.outputs.cache-hit != 'true'
          run: yarn install --frozen-lockfile
          shell: bash
