export const PR_REVIEW_DECISION = {
	APPROVED: 'APPROVED',
	CHANGES_REQUESTED: 'CHANGES_REQUESTED',
	REVIEW_REQUIRED: 'REVIEW_REQUIRED',
} as const;

export const PR_STATE = {
	CLOSED: 'CLOSED',
	MERGED: 'MERGED',
	OPEN: 'OPEN',
} as const;
