name: 'Auto PR Labeler'
description: 'Action for adding and/or removing labels on Pull Requests'
inputs:
    owner:
      description: 'Organization Name'
      required: true
      default: 'eventespresso'
    repo:
      description: 'Repository Name'
      required: true
      default: 'barista'
    prNumber:
      description: 'Pull Request Number'
      required: true
    token:
        required: true
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
