name: 'Version bumb action'
description: 'This action helps in bumping the versions in WordPress plugin files.'
author: 'eventespresso'
inputs:
    info-json-file:
        required: true
        description: 'Path of the info.json file.'
    main-file:
        required: true
        description: 'Path of the plugin main file'
    readme-file:
        required: true
        description: 'Path of the plugin readme.txt file'
    bump-type:
        required: true
        description: 'The version bump type i.e. `major` | `minor` | `patch` | `build` | `custom`'
    release-type:
        description: 'Explicit value for setting the release type while bumping the version.'
        default: 'rc'
    custom-value:
        description: 'Custom value for setting the release type or bump type (reset).'
        default: ''
runs:
    using: 'node20'
    main: 'dist/index.js'
