name: 'Version bumb action'
description: 'This action helps in bumping the versions in WordPress plugin files.'
author: 'eventespresso'
inputs:
    type:
        required: true
        description: 'The version bump type i.e. `major` | `minor` | `patch` | `release_type` | `build`'
    value:
        description: 'The value to use for bumping. Usually used to set release type or reset build.'
    main-file:
        required: true
        description: 'Path of the plugin main file'
    readme-file:
        required: true
        description: 'Path of the plugin readme.txt file'
    info-json-file:
        required: true
        description: 'Path of the info.json file.'
runs:
    using: 'node12'
    main: 'dist/index.js'
