name: 'Checkout and set up LAMP'
description: 'This action checks out the commit, sets up LAMP stack and runs composer install.'
author: 'eventespresso'
inputs:
    php-version:
        required: true
        description: 'The PHP version to set up.'
    php-tools:
        required: false
        description: 'Tools to set up for PHP.'
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
    token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
runs:
    using: 'composite'
    steps:
        - name: Checkout the commit
          uses: actions/checkout@v2
          with:
              fetch-depth: ${{ inputs.fetch-depth }}
              token: ${{ inputs.token }}

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ inputs.php-version }}
              tools: ${{ inputs.php-tools }}

        - name: Start mysql service
          run: sudo systemctl start mysql.service
          shell: bash

        - name: Get composer cache directory
          id: composercache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"
          shell: bash

        - name: Cache composer dependencies
          uses: actions/cache@v2
          with:
              path: ${{ steps.composercache.outputs.dir }}
              # Use composer.lock for key.
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

        - name: Check PHP Version
          run: php -v
          shell: bash

        - name: Composer install
          run: composer install --optimize-autoloader --prefer-dist
          shell: bash
