name: 'Checkout and set up LAMP'

description: 'This action checks out the commit, sets up LAMP stack and runs composer install.'

author: 'eventespresso'

branding:
    icon: 'calendar'
    color: 'blue'

inputs:
    php-version:
        required: true
        description: 'The PHP version to set up.'
    composer-dependencies:
        required: false
        description: 'Composer dependency version strategy to use. Options: locked (default), lowest, highest.'
        default: 'locked'
    composer-options:
        required: false
        description: 'Composer command options. Default: "--optimize-autoloader --ignore-platform-reqs".'
        default: '--optimize-autoloader --ignore-platform-reqs'
    php-tools:
        required: false
        description: 'Tools to set up for PHP.'
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
    token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
    cache-key:
        required: false
        description: 'key used for setting and reading cache.'
        default: ${{ github.cache-key }}

runs:
    using: 'composite'
    steps:
        - name: Checkout the commit
          uses: actions/checkout@v2
          with:
              fetch-depth: ${{ inputs.fetch-depth }}
              token: ${{ inputs.token }}

        - name: Set Timestamp
          id: timestamp
          shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
          run: echo "::set-output name=hour::$(date +'%Y-%m-%d-%H')"

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ inputs.php-version }}
              tools: ${{ inputs.php-tools }}

        - name: Check PHP Version
          shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
          run: php -v

        - name: Start mysql service
          shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
          run: sudo systemctl start mysql.service

#        - name: Remove vendor directory
#          shell: bash
#          run: rm -rf vendor/*

        - name: Composer install
          uses: 'ramsey/composer-install@v2'
          with:
              composer-options: ${{ inputs.composer-options }}
              dependency-versions: ${{ inputs.composer-dependencies }}
              custom-cache-key: ${{ inputs.cache-key }}-${{ steps.timestamp.outputs.hour }}

#        - name: Check Composer Dependency Versions
#          shell: bash
#          run: phpunit --version
