name: Build packages (dist)

on:
    push:
        branches: [main]
jobs:
    build-packages-to-js:
        runs-on: ubuntu-latest
        steps:
            - id: yarn-cache
              name: Get Yarn cache path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/checkout@v2
              name: Checkout the commit

            - uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - uses: actions/cache@master
              name: Load Yarn cache
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            # Build the packages
            - name: Build all packages
              run: yarn run:all

            # Commit the built assets back to the branch
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Build JS
                  commit_user_name: ${{ secrets.GIT_USER_NAME }}
                  commit_user_email: ${{ secrets.GIT_USER_EMAIL }}
