name: Build packages (dist)

on:
    push:
        branches: [main]
jobs:
    build-packages-to-js:
        # Avoid recursion
        if: "!contains(github.event.head_commit.message, 'gh-actions')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Checkout and yarn
              uses: ./packages/checkout-and-yarn
              with:
                  token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}

            # Build the packages
            - name: Build all packages
              run: yarn build

            # Commit the built assets back to the branch
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: --force # required for protected branches
                  commit_message: Build JS - gh-actions
                  commit_user_name: ${{ secrets.GH_ACTIONS_GIT_USER_NAME }}
                  commit_user_email: ${{ secrets.GH_ACTIONS_GIT_USER_EMAIL }}
