name: Build & Test CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout and yarn
              uses: ./packages/checkout-and-yarn@checkout-and-yarn-action

            - name: Run all scripts
              run: yarn run:all
